tests:
    hello:
        assertStdoutContains: '"hello":"world"'
        input:
            - ""
software:
    graphql-php:
        #execute: ["curl", "http://127.0.0.1:6000/[[tests]]"]
        execute: ["curl", "-d", '{"query": "query { echo(message: \"Hello World\") }" }', "-H", "Content-Type: application/json", "http://localhost:6000/[[tests]]"]
        install:
            - date;pwd;ls -l;mkdir x; cd x; php -r "copy('https://getcomposer.org/installer', 'composer-setup.php'); if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"; php composer-setup.php; php composer.phar  require webonyx/graphql-php -n; mv vendor ../
            #- php composer-setup.php
            #- php composer.phar 
            #- php -r "unlink('composer-setup.php');"
            #- mkdir x; cd x; composer require webonyx/graphql-php -n; mv vendor ../; cd ../
            - nohup php -S 127.0.0.1:6000 examples/00-hello-world/graphql.php &
